### ISSUE TITLE
Requirement document

### ISSUE THREAD

**Issue by pandalee99** [zuozhixiang/6.8540#1]
Can you make a markdown file that describes the project and tells me what the Lab is about?
@zuozhixiang

**Comment by zuozhixiang** [comment]
ok，to add readme later


 ***@***.***
 ***@***.***
  



---- Replied Message ----
From  ***@***.***> Date  05/15/2024 20:37 To  ***@***.***> Cc  ***@***.***> Subject  [zuozhixiang/6.8540] Requirement document (Issue #1)  

Can you make a markdown file that describes the project and tells me what the Lab is about?

**Comment by pandalee99** [comment]
pretty good !
